import json
import importlib.util
from pathlib import Path
from collections import defaultdict
from transformers import AutoTokenizer, AutoConfig

SUB = Path("/workspace/XXP_VAL152/submission.json")

ROOT = Path(
    "/workspace/Knowledge_Store/"
    "val_extracted/converted_datastore/text_related"
)

TSTORE = ROOT / "text_related_store_text_val"
ISTORE = ROOT / "image_related_store_text_val"

STAGE8A = Path(
    "/workspace/STAGE8B_HANDOFF_FINAL/scripts/"
    "stage8a_freeze_evidence_FIXED.py"
)

OUT_RAW = Path("/workspace/XXP_VAL152/recovered_with_urls.json")
OUT_AUDIT = Path("/workspace/XXP_VAL152/url_recovery_audit.json")


# -------------------------------------------------
# Load historical canon()/freeze_xxp() EXACTLY
# -------------------------------------------------

spec = importlib.util.spec_from_file_location(
    "stage8a_old", STAGE8A
)
old = importlib.util.module_from_spec(spec)
spec.loader.exec_module(old)

canon = old.canon
freeze_xxp = old.freeze_xxp


# -------------------------------------------------
# SigLIP tokenizer config used by official XxP
# -------------------------------------------------

MODEL = "google/siglip-base-patch16-384"

tok = AutoTokenizer.from_pretrained(MODEL)
cfg = AutoConfig.from_pretrained(MODEL)

max_pos = getattr(cfg, "max_position_embeddings", 64)
chunk_n = max(1, max_pos - 4)

print("SIGLIP max_position_embeddings =", max_pos)
print("IMAGE chunk tokens =", chunk_n)


def read_jsonl(path):
    rows = []

    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            if not line:
                continue

            rows.append(json.loads(line))

    return rows


def norm(s):
    return (s or "").strip()


def build_text_candidates(path):
    """
    Exact text form generated by BM25Retriever before ranking:
      groups of 4 url2text entries joined by spaces.
    """
    out = defaultdict(list)

    for entry in read_jsonl(path):
        url = entry.get("url") or ""
        vals = entry.get("url2text", [])

        if isinstance(vals, str):
            vals = [vals]

        for i in range(0, len(vals), 4):
            text = " ".join(vals[i:i+4])

            if norm(text):
                out[norm(text)].append({
                    "url": url,
                    "channel": "TEXT",
                })

    return out


def chunk_text(text):
    ids = tok.encode(
        text,
        add_special_tokens=False
    )

    result = []

    for i in range(0, len(ids), chunk_n):
        sub = ids[i:i+chunk_n]

        x = tok.decode(
            sub,
            clean_up_tokenization_spaces=True
        ).strip()

        if x:
            result.append(x)

    return result


def build_image_candidates(path):
    """
    Exact full_text form returned by MMRetriever:
      first 3 token-aware chunks for each URL.
    """
    url_chunks = defaultdict(list)

    for entry in read_jsonl(path):
        url = entry.get("url") or ""

        vals = entry.get("url2text", [])

        if isinstance(vals, str):
            vals = [vals]

        for text_piece in vals:
            for ch in chunk_text(text_piece):
                url_chunks[url].append(ch)

    out = defaultdict(list)

    for url, chunks in url_chunks.items():
        text = "\n".join(chunks[:3])

        if norm(text):
            out[norm(text)].append({
                "url": url,
                "channel": "IMAGE",
            })

    return out


submission = json.loads(SUB.read_text())

assert len(submission) == 152

recovered = []
audit = []

total = 0
unique = 0
ambiguous = 0
missing = 0


for idx, row in enumerate(submission):

    text_map = build_text_candidates(
        TSTORE / f"{idx}.json"
    )

    image_map = build_image_candidates(
        ISTORE / f"{idx}.json"
    )

    merged_map = defaultdict(list)

    for mp in [text_map, image_map]:
        for text, hits in mp.items():
            merged_map[text].extend(hits)

    raw = []

    claim_audit = {
        "id": str(idx),
        "evidence": [],
    }

    for pos, e in enumerate(row.get("evidence") or []):

        total += 1

        text = norm(e.get("text"))
        hits = merged_map.get(text, [])

        # Unique canonical URLs only
        by_canon = {}

        for h in hits:
            cu = canon(h["url"])

            if cu:
                by_canon.setdefault(cu, []).append(h)

        urls = list(by_canon.keys())

        rec = {
            "position": pos,
            "text_prefix": text[:120],
            "canonical_urls": urls,
            "hits": hits,
        }

        if len(urls) == 1:
            unique += 1

            u = urls[0]

            # Keep source only as provenance metadata.
            channels = sorted({
                h["channel"]
                for h in by_canon[u]
            })

            raw.append({
                "text": text,
                "url": u,
                "score": 0.0,
                "source": "+".join(channels),
            })

            rec["status"] = "UNIQUE"

        elif len(urls) == 0:
            missing += 1
            rec["status"] = "MISSING"

        else:
            ambiguous += 1
            rec["status"] = "AMBIGUOUS"

        claim_audit["evidence"].append(rec)

    recovered.append({
        "id": str(idx),
        "questions": row.get("questions") or [],
        "merged_deduplicated": raw,
    })

    audit.append(claim_audit)

    if (idx + 1) % 10 == 0:
        print(
            f"{idx+1}/152 "
            f"unique={unique} "
            f"ambiguous={ambiguous} "
            f"missing={missing}",
            flush=True
        )


OUT_RAW.write_text(
    json.dumps(
        recovered,
        ensure_ascii=False,
        indent=2
    )
)

OUT_AUDIT.write_text(
    json.dumps(
        {
            "n_claims": 152,
            "total_evidence": total,
            "unique": unique,
            "ambiguous": ambiguous,
            "missing": missing,
            "claims": audit,
        },
        ensure_ascii=False,
        indent=2
    )
)


print()
print("TOTAL =", total)
print("UNIQUE =", unique)
print("AMBIGUOUS =", ambiguous)
print("MISSING =", missing)

if ambiguous == 0 and missing == 0:
    print("URL_RECOVERY_EXACT_OK")
else:
    print("URL_RECOVERY_NEEDS_REVIEW")
